AWSTemplateFormatVersion: '2010-09-09'
Description: Example of template parameters.

Parameters:
  InstanceType:
    Type: String
    Description: 'Pick an EC2 instance type to create'
    Default: 't2.micro'
    AllowedValues:
      - 't2.micro'
      - 't2.small'
      - 't2.medium'
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: 'Name of an existing EC2 key pair for SSH access.'

Resources:
  MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName



