AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: EC2 instance type

Mappings:
  RegionMap:
    us-east-1:
      InstanceType: t2.micro
    us-west-2:
      InstanceType: t2.medium
    eu-west-1:
      InstanceType: t2.small

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Fn::FindInMap:
          - RegionMap
          - !Ref "AWS::Region"
          - InstanceType
      ImageId: ami-12345678
