AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      KeyName: "hardcoded-keypair"
      ImageId: "ami-0c02fb55956c7d316"
      SubnetId: "subnet-12345678"




