AWSTemplateFormatVersion: '2010-09-09'
Description: Example of pseudo parameters.

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-my-sample-bucket"


