Resources:
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyAppLoadBalancer
      Subnets:
        - Ref: SubnetA
        - Ref: SubnetB
        - Ref: SubnetC

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      AvailabilityZone: !Select [ 0, !Fn::GetAZs '' ]


