Resources:
  MyEC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      AvailabilityZone: !Select [ 0, !Fn::GetAZs '' ]

  MyEC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      AvailabilityZone: !Select [ 1, !Fn::GetAZs '' ]

  MyEC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      AvailabilityZone: !Select [ 2, !Fn::GetAZs '' ]



